# This file contains the fastlane.tools configuration
# Fastlane configuration for WildLifeConnect project

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(
      task: "test",
      gradle_path: './gradlew' # Full path to the android directory
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
      task: "clean assembleRelease",
      gradle_path: './gradlew' # Full path to the android directory
    )
    crashlytics
    # Add any additional beta testing services here
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(
      task: "clean assembleRelease",
      gradle_path: './gradlew' # Full path to the android directory
    )
    upload_to_play_store(
       json_key_file: ENV['SERVICE_ACCOUNT_JSON_PATH'],
    )
  end
end
