# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    # Print current working directory to debug path issues
    sh "pwd"
    # List contents of the android directory to ensure gradlew is present
    sh "ls -la ./android"
  
    gradle(
      task: "test",
      gradle_path: './android/gradlew' # Adjusted to use relative path
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
      task: "clean assembleRelease",
      gradle_path: './android/gradlew' # Adjusted to use relative path
    )
    crashlytics
    # Add any additional beta testing services here
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(
      task: "clean assembleRelease",
      gradle_path: './android/gradlew' # Adjusted to use relative path
    )
    upload_to_play_store(
       json_key_file: ENV['SERVICE_ACCOUNT_JSON_PATH'],
    )
  end
end
